name: Deploy to Kubernetes
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: bitnami/kubectl:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          
      - name: Apply certs
        run: kubectl apply -f cert/
        
      - name: Apply nodes
        run: |
          helm install -n elasticsearch --create-namespace es-cluster-master elastic/elasticsearch -f master-values.yaml
          helm install -n elasticsearch --create-namespace es-cluster-data elastic/elasticsearch -f data-values.yaml
          helm install -n elasticsearch --create-namespace es-cluster-ingest elastic/elasticsearch -f ingest-values.yaml



